version: "3.9"

services:
  # ===================================
  # Primary Backend (Auth)
  # ===================================
  primary-backend:
    image: taraknathjana09/primary_backend:latest
    container_name: primary_backend
    depends_on:
      - kafka
      - timescaledb
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@timescaledb:5432/postgres"
      KAFKA_CLIENT_ID: "mykafka"
      KAFKA_TOPICs: "TRADE"
      PORT: 9078
      KAFKA_BROKER: "kafka:9092"
      KAFKA_GROUP_ID: "test-primary-backend"
      KAFKA_TOPIC: "MARKET-DATA"
      KAFKA_GROUP_ID_PRIMARY: "test-group-user-result"
      KAFKA_TOPIC_PRIMARY: "USER-TRADE"
      JWT_SECRET: "my-first-secret"
      KAFKA_GROUP_IDs: "simpol-group"
      CLIENT_URL: http://pushgateway:9091
    ports:
      - "3000:3000"
      - "9078:9078"
    restart: always
    networks:
      - backend_network

  # ===================================
  # Publish_data Service
  # ===================================
  publish_data:
    image: taraknathjana09/publish_data:latest
    container_name: publish_data
    depends_on:
      - kafka
    environment:
      PORT: 5076
      KAFKA_TOPIC: "MARKET-DATA"
      KAFKA_BROKER: "kafka:9092"
      KAFKA_GROUP_ID: "test-group-publish"
      KAFKA_CLIENT_ID: "mykafka"
      CLIENT_URL: http://pushgateway:9091
    ports:
      - "5076:5076"
    restart: always
    networks:
      - backend_network

  # ===================================
  # Poller
  # ===================================
  poller:
    image: taraknathjana09/poller:latest
    container_name: poller
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC: "MARKET-DATA"
      KAFKA_BROCKER: "kafka:9092"
      KAFKA_CLIENT_ID: "mykafka"
      CLIENT_URL: http://pushgateway:9091
    restart: always
    networks:
      - backend_network

  # ===================================
  # Engine
  # ===================================
  engine:
    image: taraknathjana09/engine:latest
    container_name: engine
    depends_on:
      - kafka
      - timescaledb
    environment:
      MARKET_KAFKA_GROUP_ID: "test-group"
      MARKET_KAFKA_TOPIC: "MARKET-DATA"
      USER_KAFKA_GROUP_ID: "test-group-user"
      USER_KAFKA_TOPIC: "TRADE"
      KAFKA_CLIENT_ID: "mykafka"
      KAFKA_BROKER: "kafka:9092"
      KAFKA_USER_TRADE_TOPIC: "USER-TRADE"
      CLIENT_URL: http://pushgateway:9091
      DATABASE_URL: "postgresql://postgres:mysecretpassword@timescaledb:5432/postgres"
    restart: always
    networks:
      - backend_network

  # ===================================
  # TimescaleDB
  # ===================================
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      - backend_network

  # ===================================
  # Apache Kafka
  # ===================================
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_HEAP_OPTS: "-Xmx1536M -Xms512M"
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 3
      KAFKA_NUM_REPLICA_FETCHERS: 1
      KAFKA_QUEUED_MAX_REQUESTS: 20
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 3000
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_CLEANER_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          memory: 2g

  # ===================================
  # Pushgateway
  # ===================================
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always

  # ===================================
  # Prometheus
  # ===================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    restart: always
    depends_on:
      - pushgateway

  # ===================================
  # Grafana
  # ===================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus

# ===================================
# Networking & Volumes
# ===================================
networks:
  backend_network:
    driver: bridge

volumes:
  kafka-data:
  timescaledb-data:
